packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  core-js: true
  prisma: true
  sharp: true

ignoredBuiltDependencies:
  - prisma

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - better-sqlite3
  - core-js
  - sharp
