import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

import { AntdRegistry } from '@ant-design/nextjs-registry'
import AntdPatch from './../AntdPatch'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AntdPatch />

        <AntdRegistry>
          <div className="rmst-root">{children}</div>
        </AntdRegistry>
      </body>
    </html>
  )
}
